// 論文 Methods 記載例（S10 エクスポート画面のコピー用文案）を組み立てる純関数群。
// 文案本文は docs/methods-boilerplate.md §1〜2 の正典から一字一句そのまま引用している。
// このモジュールはプレースホルダの自動反映・見出しのプレーンテキスト化のみを担い、
// 文案そのものは書き換えない（変更する場合は正典ドキュメントを先に改訂すること）

export type MethodsLanguage = 'en' | 'ja';
export type MethodsWorkflow = 'single' | 'dual';

/** プレースホルダへ自動反映する実績値。null / 空配列 / 0 = 反映できず {{...}} のまま残す */
export interface MethodsFacts {
  toolVersion: string | null;
  /** run_type=full の完了 run の model_version（新しい順・重複除去）。複数は「, 」区切りで列挙 */
  modelIds: string[];
  /** 同 run の provider 表示名（gemini → Gemini / openrouter → OpenRouter。重複除去） */
  providers: string[];
  /** run_type=pilot の完了 run の対象 study 数（和集合の要素数）。0 なら反映しない（{{n_pilot}} のまま） */
  pilotStudyCount: number;
  /** text_status = no_text_layer の document 数（0 ならオプション文自体を出さない） */
  scannedDocumentCount: number;
}

export interface BuiltMethodsText {
  /** コピー用プレーンテキスト（見出しは「Data extraction.」/「データ抽出.」をプレーンで先頭に付ける。§4 準拠） */
  text: string;
  /** 未反映のまま残ったプレースホルダ名（重複除去・出現順。注意書き表示の素材） */
  unresolved: string[];
}

// 見出し（§4: Markdown 太字のまま含めず、プレーンテキストとして本文先頭に付ける）
const HEADING: Record<MethodsLanguage, string> = {
  en: 'Data extraction.',
  ja: 'データ抽出.',
};

// 1 段落目（tool_version / model_id / provider / n_sample / n_pilot。単一・二重で共通。§1.1 / §2.1）
const PARAGRAPH_1: Record<MethodsLanguage, string> = {
  en: 'Data were extracted using sr-data-extraction-plugin version {{tool_version}} (https://github.com/youkiti/sr-data-extraction-plugin), an open-source browser extension for large language model (LLM)–assisted data extraction with human verification. A draft data extraction form was generated by an LLM ({{model_id}}, accessed via the {{provider}} API) from the review protocol and {{n_sample}} sample articles, and was reviewed and revised by the authors. The form was piloted on {{n_pilot}} studies and refined before full extraction.',
  ja: 'データ抽出には、オープンソースのブラウザ拡張である sr-data-extraction-plugin バージョン {{tool_version}}（https://github.com/youkiti/sr-data-extraction-plugin）を使用した。抽出フォームの草案は、レビュープロトコルとサンプル論文 {{n_sample}} 本をもとに大規模言語モデル（LLM: {{model_id}}、{{provider}} API 経由）が作成し、著者らが内容を確認・修正した。フォームは {{n_pilot}} 本の研究でパイロット抽出を行い、改訂したうえで本抽出に用いた。',
};

// 2 段落目・単一レビュアー版（§1.1 / §2.1）
const PARAGRAPH_2_SINGLE: Record<MethodsLanguage, string> = {
  en: 'For each included study, the LLM pre-extracted every item from the full-text PDF and returned, for each value, a verbatim quotation of the supporting text, which the tool located and highlighted in the source PDF. One reviewer ({{reviewer_initials}}) checked every AI-extracted value against the highlighted source text and accepted, corrected, or rejected it, or marked the item as not reported. Verification fields were initially blank and every item — including accepted values — required an explicit decision by the reviewer, so no AI-generated value entered the final dataset without human confirmation. All AI outputs (values, quotations, page locations, and confidence ratings) and all human decisions were automatically logged, and the complete audit trail is provided in {{supplement_ref}}.',
  ja: '各採用研究について、LLM が全文 PDF から各項目の値を事前抽出し、値ごとに根拠となる本文の逐語的引用を付与した。本ツールは引用箇所を PDF 上に対応付けてハイライト表示し、レビュアー 1 名（{{reviewer_initials}}）がすべての AI 抽出値を原文と照合して、承認・修正・棄却・未報告のいずれかを判定した。検証欄は空欄の状態から開始し、承認を含むすべての項目に明示的な判定操作を必須としたため、人間の確認を経ていない AI 出力が最終データセットに含まれることはない。すべての AI 出力（値・引用・ページ位置・確信度）と人間の判定は自動記録され、監査証跡の全体を {{supplement_ref}} に示す。',
};

// 2 段落目・二重独立検証 + コンセンサス版（§1.2 / §2.2）
const PARAGRAPH_2_DUAL: Record<MethodsLanguage, string> = {
  en: 'For each included study, the LLM pre-extracted every item from the full-text PDF and returned, for each value, a verbatim quotation of the supporting text, which the tool located and highlighted in the source PDF. Two reviewers ({{reviewer_initials}}) independently verified the AI-extracted values against the highlighted source text, accepting, correcting, or rejecting each value or marking it as not reported. Disagreements were resolved by discussion or, when necessary, by a third reviewer ({{adjudicator_initials}}), and the consensus values were used in the final dataset. Verification fields were initially blank and every item required an explicit decision, so no AI-generated value entered the final dataset without human confirmation. All AI outputs (values, quotations, page locations, and confidence ratings) and all human decisions were automatically logged, and the complete audit trail is provided in {{supplement_ref}}.',
  ja: '各採用研究について、LLM が全文 PDF から各項目の値を事前抽出し、値ごとに根拠となる本文の逐語的引用を付与した。本ツールは引用箇所を PDF 上に対応付けてハイライト表示し、レビュアー 2 名（{{reviewer_initials}}）が独立に、すべての AI 抽出値を原文と照合して承認・修正・棄却・未報告のいずれかを判定した。不一致は協議により解消し、必要に応じて第 3 のレビュアー（{{adjudicator_initials}}）が裁定して、コンセンサス値を最終データセットに用いた。検証欄は空欄の状態から開始し、すべての項目に明示的な判定操作を必須としたため、人間の確認を経ていない AI 出力が最終データセットに含まれることはない。すべての AI 出力（値・引用・ページ位置・確信度）と人間の判定は自動記録され、監査証跡の全体を {{supplement_ref}} に示す。',
};

// スキャン PDF（no_text_layer）のオプション文（§1.3 / §2.3。scannedDocumentCount > 0 のときだけ連結）
const OPTIONAL_SCANNED: Record<MethodsLanguage, string> = {
  en: 'For {{n_scanned}} studies available only as scanned PDFs without a text layer, the PDF was submitted directly to the LLM; supporting quotations for these studies could not be highlighted and were verified against the quoted text and reported page numbers.',
  ja: 'テキスト層を持たないスキャン PDF のみ入手可能であった {{n_scanned}} 本については、PDF を直接 LLM に送信して抽出した。これらの研究では引用箇所のハイライト表示ができないため、引用文と報告ページ番号に基づいて原文と照合した。',
};

/** text 中の {{key}} をすべて value に置換する（value が null なら手を付けず {{key}} を残す） */
function applyPlaceholder(text: string, key: string, value: string | null): string {
  if (value === null) {
    return text;
  }
  return text.split(`{{${key}}}`).join(value);
}

/** 残存する {{...}} プレースホルダ名を出現順・重複除去で列挙する */
function findUnresolvedPlaceholders(text: string): string[] {
  const tokens = text.match(/\{\{[a-zA-Z0-9_]+\}\}/g);
  /* istanbul ignore if -- 正典の文案（§1〜2）は n_sample / reviewer_initials / supplement_ref を
     必ず自動反映しないため、buildMethodsText 経由では未反映 0 件（= match が null）にはならない防御分岐 */
  if (tokens === null) {
    return [];
  }
  const names = tokens.map((token) => token.slice(2, -2));
  return Array.from(new Set(names)); // Set はキー追加順を保持するため出現順のまま重複除去できる
}

/**
 * 論文 Methods セクションの記載例を組み立てる（docs/methods-boilerplate.md §1〜2 の正典どおり）。
 * 自動反映できる実績値（tool_version / model_id / provider / n_pilot / n_scanned）はプレースホルダへ
 * 埋め込み、それ以外（n_sample / reviewer_initials / adjudicator_initials / supplement_ref）は
 * 常に {{...}} のまま残す（§3: ユーザー自身の編集を促す）
 */
export function buildMethodsText(
  language: MethodsLanguage,
  workflow: MethodsWorkflow,
  facts: MethodsFacts,
): BuiltMethodsText {
  const paragraph2 = workflow === 'dual' ? PARAGRAPH_2_DUAL[language] : PARAGRAPH_2_SINGLE[language];
  const parts = [`${HEADING[language]} ${PARAGRAPH_1[language]}`, paragraph2];
  if (facts.scannedDocumentCount > 0) {
    parts.push(OPTIONAL_SCANNED[language]);
  }
  let text = parts.join('\n\n');
  text = applyPlaceholder(text, 'tool_version', facts.toolVersion);
  text = applyPlaceholder(
    text,
    'model_id',
    facts.modelIds.length > 0 ? facts.modelIds.join(', ') : null,
  );
  text = applyPlaceholder(
    text,
    'provider',
    facts.providers.length > 0 ? facts.providers.join(', ') : null,
  );
  text = applyPlaceholder(
    text,
    'n_pilot',
    facts.pilotStudyCount > 0 ? String(facts.pilotStudyCount) : null,
  );
  text = applyPlaceholder(
    text,
    'n_scanned',
    facts.scannedDocumentCount > 0 ? String(facts.scannedDocumentCount) : null,
  );
  // n_sample / reviewer_initials / adjudicator_initials / supplement_ref は常に自動反映しない（§3）
  return { text, unresolved: findUnresolvedPlaceholders(text) };
}
