// デモ用抽出スキーマ（確定版 1 版）。brief の指定どおり study 8 項目 + arm 3 項目 +
// outcome_result 5 項目 = 16 項目。SchemaFields タブへそのまま書き込む形（domain/schemaField.ts）
// で定義し、seed.ts（シード）と llmFixtures.ts（#/schema での再確認・#/extract の一括抽出応答）の
// 両方から参照する単一の正典にする。
import type { SchemaField } from '../domain/schemaField';
import { DEMO_SCHEMA_VERSION } from './constants';

/**
 * SchemaFields の field_index はタブ内の表示順（requirements.md §3.2）。
 * section は「study 用の 4 セクション + arm + outcome」の日本語ラベルにして、
 * 実運用のスキーマ編集画面に近い見た目にする。
 */
export const DEMO_SCHEMA_FIELDS: readonly SchemaField[] = [
  // --- study level ---
  {
    schemaVersion: DEMO_SCHEMA_VERSION,
    fieldId: 'f_country',
    fieldIndex: 0,
    section: '試験概要',
    fieldName: 'country',
    fieldLabel: '国',
    entityLevel: 'study',
    dataType: 'text',
    unit: null,
    allowedValues: null,
    required: true,
    extractionInstruction: '試験が実施された国を報告どおりの表記で抽出する。',
    example: 'Iran',
    aiGenerated: true,
    note: null,
  },
  {
    schemaVersion: DEMO_SCHEMA_VERSION,
    fieldId: 'f_design',
    fieldIndex: 1,
    section: '試験概要',
    fieldName: 'study_design',
    fieldLabel: 'デザイン',
    entityLevel: 'study',
    dataType: 'text',
    unit: null,
    allowedValues: null,
    required: true,
    extractionInstruction: '試験デザイン（RCT かどうか、並行群間 / クロスオーバー等）を報告どおりに抽出する。',
    example: 'Randomized controlled trial (parallel-group)',
    aiGenerated: true,
    note: null,
  },
  {
    schemaVersion: DEMO_SCHEMA_VERSION,
    fieldId: 'f_enrollment_period',
    fieldIndex: 2,
    section: '試験概要',
    fieldName: 'enrollment_period',
    fieldLabel: '登録期間',
    entityLevel: 'study',
    dataType: 'text',
    unit: null,
    allowedValues: null,
    required: false,
    extractionInstruction: 'participant の登録（enrollment）期間を報告どおりに抽出する。',
    example: 'March 2021 to February 2022',
    aiGenerated: true,
    note: null,
  },
  {
    schemaVersion: DEMO_SCHEMA_VERSION,
    fieldId: 'f_followup_duration',
    fieldIndex: 3,
    section: '試験概要',
    fieldName: 'followup_duration',
    fieldLabel: '追跡期間',
    entityLevel: 'study',
    dataType: 'text',
    unit: null,
    allowedValues: null,
    required: false,
    extractionInstruction: 'アウトカム評価の追跡期間を報告どおりに抽出する。',
    example: 'Until hospital discharge',
    aiGenerated: true,
    note: null,
  },
  {
    schemaVersion: DEMO_SCHEMA_VERSION,
    fieldId: 'f_sample_size_total',
    fieldIndex: 4,
    section: '対象集団',
    fieldName: 'sample_size_total',
    fieldLabel: '総サンプルサイズ',
    entityLevel: 'study',
    dataType: 'integer',
    unit: null,
    allowedValues: null,
    required: true,
    extractionInstruction: '解析対象となった参加者の総数を抽出する（脱落後の最終解析数）。',
    example: '106',
    aiGenerated: true,
    note: null,
  },
  {
    schemaVersion: DEMO_SCHEMA_VERSION,
    fieldId: 'f_gestational_age',
    fieldIndex: 5,
    section: '対象集団',
    fieldName: 'gestational_age_mean_weeks',
    fieldLabel: '平均在胎週数',
    entityLevel: 'study',
    dataType: 'float',
    unit: 'weeks',
    allowedValues: null,
    required: false,
    extractionInstruction: '対象集団全体の平均在胎週数を報告どおりの単位で抽出する。',
    example: '38.4',
    aiGenerated: true,
    note: null,
  },
  {
    schemaVersion: DEMO_SCHEMA_VERSION,
    fieldId: 'f_female_percent',
    fieldIndex: 6,
    section: '対象集団',
    fieldName: 'female_percent',
    fieldLabel: '女児割合',
    entityLevel: 'study',
    dataType: 'float',
    unit: '%',
    allowedValues: null,
    required: false,
    extractionInstruction: '対象集団全体に占める女児の割合を報告どおりに抽出する。',
    example: '47.2',
    aiGenerated: true,
    note: null,
  },
  {
    schemaVersion: DEMO_SCHEMA_VERSION,
    fieldId: 'f_funding_source',
    fieldIndex: 7,
    section: '試験概要',
    fieldName: 'funding_source',
    fieldLabel: '資金源',
    entityLevel: 'study',
    dataType: 'text',
    unit: null,
    allowedValues: null,
    required: false,
    extractionInstruction: '資金提供元（助成金・財団・企業等）を報告どおりに抽出する。記載が無ければ not_reported とする。',
    example: null,
    aiGenerated: true,
    note: null,
  },
  // --- arm level ---
  {
    schemaVersion: DEMO_SCHEMA_VERSION,
    fieldId: 'f_arm_name',
    fieldIndex: 8,
    section: '群構成',
    fieldName: 'arm_name',
    fieldLabel: '群名',
    entityLevel: 'arm',
    dataType: 'text',
    unit: null,
    allowedValues: null,
    required: true,
    extractionInstruction: '各群の名称を報告どおりに抽出する。',
    example: 'UDCA plus phototherapy group',
    aiGenerated: true,
    note: null,
  },
  {
    schemaVersion: DEMO_SCHEMA_VERSION,
    fieldId: 'f_arm_n',
    fieldIndex: 9,
    section: '群構成',
    fieldName: 'arm_n',
    fieldLabel: '群の N',
    entityLevel: 'arm',
    dataType: 'integer',
    unit: null,
    allowedValues: null,
    required: true,
    extractionInstruction: '各群の解析対象人数を抽出する。',
    example: '53',
    aiGenerated: true,
    note: null,
  },
  {
    schemaVersion: DEMO_SCHEMA_VERSION,
    fieldId: 'f_arm_intervention',
    fieldIndex: 10,
    section: '群構成',
    fieldName: 'arm_intervention',
    fieldLabel: '介入内容',
    entityLevel: 'arm',
    dataType: 'text',
    unit: null,
    allowedValues: null,
    required: true,
    extractionInstruction: '各群の介入内容（用量・投与方法を含む）を報告どおりに抽出する。',
    example: 'Oral UDCA 10 mg/kg/day',
    aiGenerated: true,
    note: null,
  },
  // --- outcome_result level ---
  {
    schemaVersion: DEMO_SCHEMA_VERSION,
    fieldId: 'f_outcome_name',
    fieldIndex: 11,
    section: 'アウトカム',
    fieldName: 'outcome_name',
    fieldLabel: 'アウトカム名',
    entityLevel: 'outcome_result',
    dataType: 'text',
    unit: null,
    allowedValues: null,
    required: true,
    extractionInstruction: 'アウトカムの名称を報告どおりに抽出する。',
    example: 'Reduction in total serum bilirubin',
    aiGenerated: true,
    note: null,
  },
  {
    schemaVersion: DEMO_SCHEMA_VERSION,
    fieldId: 'f_outcome_timepoint',
    fieldIndex: 12,
    section: 'アウトカム',
    fieldName: 'outcome_timepoint',
    fieldLabel: '測定時点',
    entityLevel: 'outcome_result',
    dataType: 'text',
    unit: null,
    allowedValues: null,
    required: true,
    extractionInstruction: 'アウトカムの測定時点を報告どおりに抽出する。',
    example: '24 hours after enrollment',
    aiGenerated: true,
    note: null,
  },
  {
    schemaVersion: DEMO_SCHEMA_VERSION,
    fieldId: 'f_outcome_events',
    fieldIndex: 13,
    section: 'アウトカム',
    fieldName: 'outcome_events',
    fieldLabel: 'イベント数',
    entityLevel: 'outcome_result',
    dataType: 'text',
    unit: null,
    allowedValues: null,
    required: false,
    extractionInstruction: '二値アウトカムのイベント数（分母含む）を抽出する。連続値アウトカムは not_reported とする。',
    example: '12/53',
    aiGenerated: true,
    note: null,
  },
  {
    schemaVersion: DEMO_SCHEMA_VERSION,
    fieldId: 'f_outcome_mean_sd',
    fieldIndex: 14,
    section: 'アウトカム',
    fieldName: 'outcome_mean_sd',
    fieldLabel: '平均・SD',
    entityLevel: 'outcome_result',
    dataType: 'text',
    unit: null,
    allowedValues: null,
    required: false,
    extractionInstruction: '連続値アウトカムの平均値・SD を報告どおりの単位で抽出する。',
    example: '6.8 (1.4) mg/dL',
    aiGenerated: true,
    note: null,
  },
  {
    schemaVersion: DEMO_SCHEMA_VERSION,
    fieldId: 'f_outcome_effect_size',
    fieldIndex: 15,
    section: 'アウトカム',
    fieldName: 'outcome_effect_size',
    fieldLabel: '効果量',
    entityLevel: 'outcome_result',
    dataType: 'text',
    unit: null,
    allowedValues: null,
    required: false,
    extractionInstruction: '群間比較の効果量（平均差・リスク比等。信頼区間含む）を報告どおりに抽出する。',
    example: 'Mean difference -1.9 mg/dL (95% CI -2.6 to -1.2)',
    aiGenerated: true,
    note: null,
  },
];
